name: Deploy

env:
  REPOSITORY_NAME: ${{ github.event.repository.name }}

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      HOST: angron42.pp.ua
      USERNAME: root
      KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      PORT: 22

    steps:

    - name: Stop server
      uses: appleboy/ssh-action@master
      with:
        host: HOST
        username: USERNAME
        key: KEY
        port: PORT
        script: |
          screen -wipe
          if screen -list | grep -q "sute-schedule-bot"; then
            screen -X -S sute-schedule-bot quit;
          fi

    - name: Pull changes
      uses: appleboy/ssh-action@master
      with:
        host: HOST
        username: USERNAME
        key: KEY
        port: PORT
        script: |
          cd ~/sute-schedule-bot
          git pull -f origin master

    - name: Setup
      uses: appleboy/ssh-action@master
      with:
        host: HOST
        username: USERNAME
        key: KEY
        port: PORT
        script: |
          cd ~/sute-schedule-bot
          pip install -r requirements.txt
          cd ~/bot-data
          echo '${{ secrets.ENV }}' > .env

    - name: Run
      uses: appleboy/ssh-action@master
      with:
        host: HOST
        username: USERNAME
        key: KEY
        port: PORT
        script: bash ~/bot-data/run.sh
